# -*- coding: utf-8 -*-
"""Assignment 2 Question 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mawbYN8hQFJ0iKMT-ZoFU9qJUcQm82Fv

# 4. House Price Prediction
"""

import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('train.csv')
df.head()

len(df)

df.columns

df.drop_duplicates(inplace=True)
len(df)

Nan_dict={}
for i in df.columns:
  if df[i].isna().sum()!=0:
    Nan_dict[i]=df[i].isna().sum()
Nan_dict

df.info()

df[['BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF']][df.BsmtExposure.isna()]

fillna_NA=[
 'Alley',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PoolQC',
 'Fence',
 'MiscFeature']

df[['YearBuilt', 'YearRemodAdd','GarageYrBlt']].corr()

df.GarageYrBlt.fillna(df.YearBuilt,inplace=True)
df.LotFrontage.fillna(df.LotFrontage.median(),inplace=True)
df.BsmtExposure[(df.BsmtExposure.isna()) & (df.BsmtCond.notna())].fillna('No',inplace=True)
for i in fillna_NA:
  df[i].fillna('NA',inplace=True)

df.Electrical.fillna(df.Electrical.mode()[0],inplace=True)
df.MasVnrType.fillna('None',inplace=True)
df.MasVnrArea.fillna(0,inplace=True)

df.info()

objectlist=[]
for i in df.columns:
  if df[i].dtype=='object':
    objectlist.append(i)

objectlist

from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

for i in objectlist:
  df[i]=lb.fit_transform(df[i])
df.head()

x=df.drop(['Id', 'MSSubClass','SalePrice'],1)
y=df.SalePrice

from sklearn.ensemble import RandomForestRegressor
rfg=RandomForestRegressor()

from sklearn.linear_model import LinearRegression
lr=LinearRegression()

rfg.fit(x,y)

rfg.score(x,y)

lr.fit(x,y)
lr.score(x,y)

### Testing

dftest=pd.read_csv('test.csv')
dftest

dftest.drop_duplicates(inplace=True)

dftest.info()

dftest.GarageYrBlt.fillna(dftest.YearBuilt,inplace=True)
dftest.LotFrontage.fillna(dftest.LotFrontage.median(),inplace=True)
dftest.BsmtExposure[(dftest.BsmtExposure.isna()) & (dftest.BsmtCond.notna())].fillna('No',inplace=True)
for i in fillna_NA:
  dftest[i].fillna('NA',inplace=True)

dftest.Electrical.fillna(dftest.Electrical.mode()[0],inplace=True)
dftest.MasVnrType.fillna('None',inplace=True)
dftest.MasVnrArea.fillna(0,inplace=True)

dftest.info()

dtest_Nan_dict={}
for i in dftest.columns:
  if dftest[i].isna().sum()!=0:
    dtest_Nan_dict[i]=dftest[i].isna().sum()
dtest_Nan_dict

modelist=['MSZoning',
 'Utilities',
 'Exterior1st',
 'Exterior2nd',
 'KitchenQual',
 'Functional',
 'SaleType']

nalist=['GarageCars',
 'GarageArea', 
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 'BsmtFullBath',
 'BsmtHalfBath']

for i in modelist:
  dftest[i].fillna(dftest[i].mode()[0],inplace=True)

for i in nalist:
  dftest[i].fillna(0,inplace=True)

dftest.info()

objectlist_testset=[]
for i in dftest.columns:
  if dftest[i].dtype=='object':
    objectlist_testset.append(i)

for i in objectlist_testset:
  dftest[i]=lb.fit_transform(dftest[i])

xtest=dftest.drop(['Id', 'MSSubClass',],1)

dftest['SalePrice']=lr.predict(xtest)

output=dftest[['Id','SalePrice']]
output.to_csv('Output.csv')